services:
  # Backend Service
  - type: web
    name: edunavigator-backend
    runtime: node
    plan: free
    buildCommand: cd learning-server && npm install
    startCommand: cd learning-server && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
    
  # Frontend Service  
  - type: web
    name: edunavigator-frontend
    runtime: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: edunavigator-backend
          property: url
      - key: VITE_APP_TITLE
        value: EduNavigator
      - key: VITE_APP_DESCRIPTION
        value: AI-Powered Career & Skills Mentor